name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: JEONTAK/Commit-Time-@master
        env:
          GH_TOKEN: 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
          GIST_ID: 1c551b1f449ddac4ff3acd42a74817cb
          LOCALE: ko-KR
